CREATE TABLE DAILY_HELP_PROFESSIONAL_SLOTS (
    SLOT_ID VARCHAR2(64 CHAR) NOT NULL,
    PROFESSIONAL_ID VARCHAR2(64 CHAR) NOT NULL,
    SLOT_DATE DATE NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'AVAILABLE' NOT NULL,
    BOOKING_ID VARCHAR2(64 CHAR),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DH_PROF_SLOTS PRIMARY KEY (SLOT_ID),
    CONSTRAINT FK_DH_SLOT_PROF FOREIGN KEY (PROFESSIONAL_ID) REFERENCES DAILY_HELP_PROFESSIONALS(PROFESSIONAL_ID),
    CONSTRAINT CK_DH_SLOT_STATUS CHECK (STATUS IN ('AVAILABLE', 'BOOKED', 'CANCELLED')),
    CONSTRAINT CK_DH_SLOT_TIME CHECK (END_TIME > START_TIME),
    CONSTRAINT UK_DH_PROF_SLOT UNIQUE (PROFESSIONAL_ID, SLOT_DATE, START_TIME, END_TIME)
);

CREATE INDEX IDX_DH_SLOT_SEARCH ON DAILY_HELP_PROFESSIONAL_SLOTS (SLOT_DATE, STATUS, PROFESSIONAL_ID);
CREATE INDEX IDX_DH_SLOT_PROF ON DAILY_HELP_PROFESSIONAL_SLOTS (PROFESSIONAL_ID, SLOT_DATE, STATUS);