-- Extend the applied Daily Help schema without modifying existing Flyway migrations.

ALTER TABLE DAILY_HELP_BOOKINGS ADD (
    OTP_EXPIRES_AT TIMESTAMP,
    OTP_ATTEMPTS NUMBER(5) DEFAULT 0 NOT NULL
);

CREATE TABLE DAILY_HELP_PROFESSIONAL_SLOTS (
    SLOT_ID VARCHAR2(64 CHAR) NOT NULL,
    PROFESSIONAL_ID VARCHAR2(64 CHAR) NOT NULL,
    SLOT_DATE DATE NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'AVAILABLE' NOT NULL,
    BOOKING_ID VARCHAR2(64 CHAR),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DH_PROF_SLOT PRIMARY KEY (SLOT_ID),
    CONSTRAINT FK_DH_SLOT_PROF FOREIGN KEY (PROFESSIONAL_ID)
        REFERENCES DAILY_HELP_PROFESSIONALS(PROFESSIONAL_ID) ON DELETE CASCADE,
    CONSTRAINT UK_DH_PROF_SLOT UNIQUE (PROFESSIONAL_ID, SLOT_DATE, START_TIME, END_TIME)
);

CREATE INDEX IDX_DH_SLOT_LOOKUP
    ON DAILY_HELP_PROFESSIONAL_SLOTS (SLOT_DATE, STATUS, PROFESSIONAL_ID);

CREATE INDEX IDX_DH_BOOK_PROF
    ON DAILY_HELP_BOOKINGS (PROFESSIONAL_ID, STATUS, SCHEDULED_START);

CREATE INDEX IDX_DH_BOOK_MATCH
    ON DAILY_HELP_BOOKINGS (STATUS, LOCALITY, SCHEDULED_START);

CREATE INDEX IDX_DH_SERVICE_ACTIVE
    ON DAILY_HELP_SERVICES (ACTIVE, CATEGORY);