-- Recovery-safe Daily Help extensions.
-- This migration may be retried after Oracle DDL has partially applied.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'DAILY_HELP_BOOKINGS'
       AND COLUMN_NAME = 'OTP_EXPIRES_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DAILY_HELP_BOOKINGS ADD (OTP_EXPIRES_AT TIMESTAMP)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'DAILY_HELP_BOOKINGS'
       AND COLUMN_NAME = 'OTP_ATTEMPTS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DAILY_HELP_BOOKINGS ADD (OTP_ATTEMPTS NUMBER(5) DEFAULT 0 NOT NULL)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'DAILY_HELP_PROFESSIONAL_SLOTS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE DAILY_HELP_PROFESSIONAL_SLOTS (
                SLOT_ID VARCHAR2(64 CHAR) NOT NULL,
                PROFESSIONAL_ID VARCHAR2(64 CHAR) NOT NULL,
                SLOT_DATE DATE NOT NULL,
                START_TIME TIMESTAMP NOT NULL,
                END_TIME TIMESTAMP NOT NULL,
                STATUS VARCHAR2(20 CHAR) DEFAULT 'AVAILABLE' NOT NULL,
                BOOKING_ID VARCHAR2(64 CHAR),
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT PK_DH_PROF_SLOT PRIMARY KEY (SLOT_ID),
                CONSTRAINT FK_DH_SLOT_PROF FOREIGN KEY (PROFESSIONAL_ID)
                    REFERENCES DAILY_HELP_PROFESSIONALS(PROFESSIONAL_ID) ON DELETE CASCADE,
                CONSTRAINT UK_DH_PROF_SLOT UNIQUE
                    (PROFESSIONAL_ID, SLOT_DATE, START_TIME, END_TIME)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    -- Oracle rejects an index when the same column list is already indexed,
    -- even if that existing index has a different name. Check both name and
    -- ordered column list so this migration is safe after partial attempts.

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES i
     WHERE i.TABLE_NAME = 'DAILY_HELP_PROFESSIONAL_SLOTS'
       AND (i.INDEX_NAME = 'IDX_DH_SLOT_LOOKUP'
            OR (SELECT LISTAGG(c.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY c.COLUMN_POSITION)
                  FROM USER_IND_COLUMNS c
                 WHERE c.INDEX_NAME = i.INDEX_NAME
                   AND c.TABLE_NAME = i.TABLE_NAME)
               = 'SLOT_DATE,STATUS,PROFESSIONAL_ID');
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_DH_SLOT_LOOKUP ON DAILY_HELP_PROFESSIONAL_SLOTS (SLOT_DATE, STATUS, PROFESSIONAL_ID)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES i
     WHERE i.TABLE_NAME = 'DAILY_HELP_BOOKINGS'
       AND (i.INDEX_NAME = 'IDX_DH_BOOK_PROF'
            OR (SELECT LISTAGG(c.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY c.COLUMN_POSITION)
                  FROM USER_IND_COLUMNS c
                 WHERE c.INDEX_NAME = i.INDEX_NAME
                   AND c.TABLE_NAME = i.TABLE_NAME)
               = 'PROFESSIONAL_ID,STATUS,SCHEDULED_START');
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_DH_BOOK_PROF ON DAILY_HELP_BOOKINGS (PROFESSIONAL_ID, STATUS, SCHEDULED_START)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES i
     WHERE i.TABLE_NAME = 'DAILY_HELP_BOOKINGS'
       AND (i.INDEX_NAME = 'IDX_DH_BOOK_MATCH'
            OR (SELECT LISTAGG(c.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY c.COLUMN_POSITION)
                  FROM USER_IND_COLUMNS c
                 WHERE c.INDEX_NAME = i.INDEX_NAME
                   AND c.TABLE_NAME = i.TABLE_NAME)
               = 'STATUS,LOCALITY,SCHEDULED_START');
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_DH_BOOK_MATCH ON DAILY_HELP_BOOKINGS (STATUS, LOCALITY, SCHEDULED_START)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES i
     WHERE i.TABLE_NAME = 'DAILY_HELP_SERVICES'
       AND (i.INDEX_NAME = 'IDX_DH_SERVICE_ACTIVE'
            OR (SELECT LISTAGG(c.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY c.COLUMN_POSITION)
                  FROM USER_IND_COLUMNS c
                 WHERE c.INDEX_NAME = i.INDEX_NAME
                   AND c.TABLE_NAME = i.TABLE_NAME)
               = 'ACTIVE,CATEGORY');
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_DH_SERVICE_ACTIVE ON DAILY_HELP_SERVICES (ACTIVE, CATEGORY)';
    END IF;
END;
/
