CREATE TABLE USER_ADDRESSES (
    ADDRESS_ID VARCHAR2(64) PRIMARY KEY,
    USER_ID VARCHAR2(64) NOT NULL,
    LABEL VARCHAR2(50) NOT NULL,
    ADDRESS_LINE1 VARCHAR2(300) NOT NULL,
    LANDMARK VARCHAR2(200),
    FORMATTED_ADDRESS VARCHAR2(500),
    PLACE_ID VARCHAR2(255),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    IS_DEFAULT NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_USER_ADDRESSES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE INDEX IDX_USER_ADDRESSES_USER ON USER_ADDRESSES(USER_ID);
CREATE INDEX IDX_USER_ADDRESSES_DEFAULT ON USER_ADDRESSES(USER_ID, IS_DEFAULT);