-- Clean schema reset for KuraliUpdates Bazaar.
-- This migration intentionally drops and recreates application tables.
-- Flyway schema history is NOT dropped.
-- V1-V3 remain historical; V4 is retired because it was never successfully applied.

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'USER_ADDRESSES','USER_SESSIONS','AUTH_OTPS','CHAT_MESSAGES',
      'NEGOTIATION_CHATS','ORDER_ITEMS','ORDERS','COUPONS',
      'BILL_DISCOUNTS','PRODUCTS','DELIVERY_AGENTS','SELLERS','USERS'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

CREATE TABLE SELLERS (
  SELLER_ID VARCHAR2(64) PRIMARY KEY,
  STORE_NAME VARCHAR2(255) NOT NULL,
  OWNER_NAME VARCHAR2(150) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL UNIQUE,
  PHONE VARCHAR2(30) NOT NULL,
  AVATAR_URL VARCHAR2(500),
  CATEGORY VARCHAR2(100) NOT NULL,
  ADDRESS VARCHAR2(500) NOT NULL,
  LOCALITY VARCHAR2(150) NOT NULL,
  DISTANCE_KM NUMBER(5,2) DEFAULT 1.0,
  RATING NUMBER(3,2) DEFAULT 0.0,
  REVIEW_COUNT NUMBER(10) DEFAULT 0,
  STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN ('PENDING','APPROVED','REJECTED')),
  GST_NUMBER VARCHAR2(50),
  FSSAI_NUMBER VARCHAR2(50),
  MIN_ORDER_FREE_DELIVERY NUMBER(10,2) DEFAULT 499.00,
  BASE_DELIVERY_FEE NUMBER(10,2) DEFAULT 35.00,
  DESCRIPTION CLOB,
  REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  APPROVED_AT TIMESTAMP
);

CREATE TABLE PRODUCTS (
  PRODUCT_ID VARCHAR2(64) PRIMARY KEY,
  SELLER_ID VARCHAR2(64) NOT NULL REFERENCES SELLERS(SELLER_ID) ON DELETE CASCADE,
  TITLE VARCHAR2(255) NOT NULL,
  CATEGORY VARCHAR2(100) NOT NULL,
  DESCRIPTION CLOB,
  IMAGE_URL VARCHAR2(500),
  MRP NUMBER(10,2) NOT NULL,
  SELLER_PRICE NUMBER(10,2) NOT NULL,
  ADDITIONAL_DISCOUNT_PCT NUMBER(5,2) DEFAULT 0.0,
  EFFECTIVE_PRICE NUMBER(10,2) GENERATED ALWAYS AS (ROUND(SELLER_PRICE * (1 - ADDITIONAL_DISCOUNT_PCT / 100), 2)),
  STOCK NUMBER(10) DEFAULT 0,
  UNIT VARCHAR2(50) DEFAULT '1 Piece',
  TAGS VARCHAR2(500),
  IS_FEATURED NUMBER(1) DEFAULT 0 CHECK (IS_FEATURED IN (0,1)),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_PROD_SELLER ON PRODUCTS(SELLER_ID);
CREATE INDEX IDX_PROD_CAT ON PRODUCTS(CATEGORY);

CREATE TABLE BILL_DISCOUNTS (
  RULE_ID VARCHAR2(64) PRIMARY KEY,
  SELLER_ID VARCHAR2(64) NOT NULL REFERENCES SELLERS(SELLER_ID) ON DELETE CASCADE,
  MIN_BILL_AMOUNT NUMBER(10,2) NOT NULL,
  DISCOUNT_PCT NUMBER(5,2),
  FLAT_DISCOUNT NUMBER(10,2),
  DESCRIPTION VARCHAR2(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_BILL_DISC_SELLER ON BILL_DISCOUNTS(SELLER_ID);

CREATE TABLE COUPONS (
  COUPON_ID VARCHAR2(64) PRIMARY KEY,
  CODE VARCHAR2(50) NOT NULL UNIQUE,
  SELLER_ID VARCHAR2(64) DEFAULT 'ALL',
  DISCOUNT_TYPE VARCHAR2(20) NOT NULL CHECK (DISCOUNT_TYPE IN ('FLAT','PERCENTAGE')),
  DISCOUNT_VALUE NUMBER(10,2) NOT NULL,
  MIN_ORDER_VALUE NUMBER(10,2) DEFAULT 0.0,
  MAX_DISCOUNT NUMBER(10,2),
  EXPIRY_DATE DATE NOT NULL,
  DESCRIPTION VARCHAR2(255),
  IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DELIVERY_AGENTS (
  AGENT_ID VARCHAR2(64) PRIMARY KEY,
  FULL_NAME VARCHAR2(150) NOT NULL,
  PHONE VARCHAR2(30) NOT NULL UNIQUE,
  EMAIL VARCHAR2(255) NOT NULL UNIQUE,
  AVATAR_URL VARCHAR2(500),
  VEHICLE_TYPE VARCHAR2(50) NOT NULL CHECK (VEHICLE_TYPE IN ('Bike','Scooter','Electric Bike','Auto / Van')),
  VEHICLE_NUMBER VARCHAR2(50) NOT NULL,
  LICENSE_NUMBER VARCHAR2(50) NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE','OFFLINE','SUSPENDED','PENDING')),
  RATING NUMBER(3,2) DEFAULT 5.0,
  TOTAL_TRIPS NUMBER(10) DEFAULT 0,
  TODAY_EARNINGS NUMBER(10,2) DEFAULT 0.0,
  TOTAL_EARNINGS NUMBER(12,2) DEFAULT 0.0,
  CURRENT_LOCALITY VARCHAR2(150) NOT NULL,
  CURRENT_LATITUDE NUMBER(10,7),
  CURRENT_LONGITUDE NUMBER(10,7),
  LOCATION_UPDATED_AT TIMESTAMP,
  REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USERS (
  USER_ID VARCHAR2(64) PRIMARY KEY,
  EMAIL VARCHAR2(255) UNIQUE,
  PHONE VARCHAR2(30) UNIQUE,
  NAME VARCHAR2(150) NOT NULL,
  ROLE VARCHAR2(30) DEFAULT 'BUYER' CHECK (ROLE IN ('BUYER','SELLER','DELIVERY','ADMIN')),
  LOCALITY VARCHAR2(150),
  ADDRESS VARCHAR2(500),
  ADDRESS_LINE1 VARCHAR2(300),
  LANDMARK VARCHAR2(200),
  FORMATTED_ADDRESS VARCHAR2(500),
  PLACE_ID VARCHAR2(255),
  LATITUDE NUMBER(10,7),
  LONGITUDE NUMBER(10,7),
  IS_VERIFIED NUMBER(1) DEFAULT 1 CHECK (IS_VERIFIED IN (0,1)),
  IS_ADMIN NUMBER(1) DEFAULT 0 CHECK (IS_ADMIN IN (0,1)),
  AVATAR_URL VARCHAR2(500),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CHK_USER_CONTACT CHECK (EMAIL IS NOT NULL OR PHONE IS NOT NULL)
);

CREATE TABLE USER_ADDRESSES (
  ADDRESS_ID VARCHAR2(64) PRIMARY KEY,
  USER_ID VARCHAR2(64) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
  LABEL VARCHAR2(50) NOT NULL,
  ADDRESS_LINE1 VARCHAR2(300) NOT NULL,
  LANDMARK VARCHAR2(200),
  FORMATTED_ADDRESS VARCHAR2(500),
  PLACE_ID VARCHAR2(255),
  LATITUDE NUMBER(10,7),
  LONGITUDE NUMBER(10,7),
  IS_DEFAULT NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_DEFAULT IN (0,1)),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_USER_ADDR_USER ON USER_ADDRESSES(USER_ID);
CREATE INDEX IDX_USER_ADDR_DEFAULT ON USER_ADDRESSES(USER_ID, IS_DEFAULT);

CREATE TABLE ORDERS (
  ORDER_ID VARCHAR2(64) PRIMARY KEY,
  BUYER_NAME VARCHAR2(150) NOT NULL,
  BUYER_PHONE VARCHAR2(30) NOT NULL,
  BUYER_EMAIL VARCHAR2(255),
  DELIVERY_ADDRESS VARCHAR2(500) NOT NULL,
  DELIVERY_LOCALITY VARCHAR2(150) NOT NULL,
  DELIVERY_LATITUDE NUMBER(10,7),
  DELIVERY_LONGITUDE NUMBER(10,7),
  DELIVERY_PLACE_ID VARCHAR2(255),
  SELLER_ID VARCHAR2(64) NOT NULL REFERENCES SELLERS(SELLER_ID),
  SUBTOTAL NUMBER(10,2) NOT NULL,
  BILL_DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0.0,
  COUPON_DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0.0,
  COUPON_CODE VARCHAR2(50),
  DELIVERY_FEE NUMBER(10,2) DEFAULT 0.0,
  IS_FREE_DELIVERY NUMBER(1) DEFAULT 0 CHECK (IS_FREE_DELIVERY IN (0,1)),
  TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
  PAYMENT_METHOD VARCHAR2(30) NOT NULL CHECK (PAYMENT_METHOD IN ('UPI','Card','COD','NetBanking')),
  PAYMENT_STATUS VARCHAR2(30) DEFAULT 'PENDING' CHECK (PAYMENT_STATUS IN ('PAID','PENDING_COD','FAILED')),
  STATUS VARCHAR2(40) DEFAULT 'PLACED' CHECK (STATUS IN ('PLACED','ACCEPTED_BY_SELLER','READY_FOR_PICKUP','ASSIGNED_TO_DELIVERY','PICKED_UP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')),
  DELIVERY_AGENT_ID VARCHAR2(64) REFERENCES DELIVERY_AGENTS(AGENT_ID),
  DELIVERY_OTP VARCHAR2(6) NOT NULL,
  DISTANCE_KM NUMBER(5,2) DEFAULT 1.5,
  ESTIMATED_DELIVERY_MINS NUMBER(5) DEFAULT 25,
  PLACED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_ORDER_SELLER ON ORDERS(SELLER_ID);
CREATE INDEX IDX_ORDER_AGENT ON ORDERS(DELIVERY_AGENT_ID);
CREATE INDEX IDX_ORDER_STATUS ON ORDERS(STATUS);

CREATE TABLE ORDER_ITEMS (
  ITEM_ID VARCHAR2(64) PRIMARY KEY,
  ORDER_ID VARCHAR2(64) NOT NULL REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
  PRODUCT_ID VARCHAR2(64) NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
  QUANTITY NUMBER(5) NOT NULL,
  UNIT_PRICE NUMBER(10,2) NOT NULL,
  NEGOTIATED_PRICE NUMBER(10,2),
  TOTAL_PRICE NUMBER(10,2) NOT NULL
);
CREATE INDEX IDX_ITEM_ORDER ON ORDER_ITEMS(ORDER_ID);

CREATE TABLE NEGOTIATION_CHATS (
  CHAT_ID VARCHAR2(64) PRIMARY KEY,
  PRODUCT_ID VARCHAR2(64) NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
  SELLER_ID VARCHAR2(64) NOT NULL REFERENCES SELLERS(SELLER_ID),
  BUYER_NAME VARCHAR2(150) NOT NULL,
  BUYER_EMAIL VARCHAR2(255) NOT NULL,
  CURRENT_AGREED_PRICE NUMBER(10,2),
  LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_CHAT_SELLER ON NEGOTIATION_CHATS(SELLER_ID);
CREATE INDEX IDX_CHAT_PROD ON NEGOTIATION_CHATS(PRODUCT_ID);

CREATE TABLE CHAT_MESSAGES (
  MESSAGE_ID VARCHAR2(64) PRIMARY KEY,
  CHAT_ID VARCHAR2(64) NOT NULL REFERENCES NEGOTIATION_CHATS(CHAT_ID) ON DELETE CASCADE,
  SENDER_ROLE VARCHAR2(20) NOT NULL CHECK (SENDER_ROLE IN ('BUYER','SELLER')),
  SENDER_NAME VARCHAR2(150) NOT NULL,
  MESSAGE_TEXT CLOB NOT NULL,
  OFFER_PRICE NUMBER(10,2),
  OFFER_STATUS VARCHAR2(20) CHECK (OFFER_STATUS IN ('PENDING','ACCEPTED','REJECTED','COUNTERED')),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_MSG_CHAT ON CHAT_MESSAGES(CHAT_ID);

CREATE TABLE AUTH_OTPS (
  OTP_ID VARCHAR2(64) PRIMARY KEY,
  IDENTIFIER VARCHAR2(255) NOT NULL,
  OTP_CODE VARCHAR2(64) NOT NULL,
  OTP_TYPE VARCHAR2(20) NOT NULL CHECK (OTP_TYPE IN ('EMAIL','PHONE')),
  IS_USED NUMBER(1) DEFAULT 0 CHECK (IS_USED IN (0,1)),
  ATTEMPTS NUMBER(2) DEFAULT 0,
  EXPIRES_AT TIMESTAMP NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_AUTH_OTPS_ID ON AUTH_OTPS(IDENTIFIER, OTP_TYPE, IS_USED);

CREATE TABLE USER_SESSIONS (
  SESSION_TOKEN VARCHAR2(128) PRIMARY KEY,
  USER_ID VARCHAR2(64) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT TIMESTAMP NOT NULL
);
CREATE INDEX IDX_SESSIONS_USER ON USER_SESSIONS(USER_ID);

COMMIT;