CREATE TABLE SEARCH_TRENDS (
    SEARCH_ID VARCHAR2(64 CHAR) NOT NULL,
    QUERY_TEXT VARCHAR2(255 CHAR) NOT NULL,
    NORMALIZED_QUERY VARCHAR2(255 CHAR) NOT NULL,
    USER_ID VARCHAR2(64 CHAR),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SEARCH_TRENDS PRIMARY KEY (SEARCH_ID)
);

CREATE INDEX IDX_SEARCH_TRENDS_QUERY ON SEARCH_TRENDS (NORMALIZED_QUERY);
CREATE INDEX IDX_SEARCH_TRENDS_CREATED ON SEARCH_TRENDS (CREATED_AT);
