-- Daily Help workflow schema.
-- V5 resets the core marketplace tables; this migration owns the Daily Help tables.
-- Safe for a fresh deployment and for environments where an earlier partial Daily Help
-- schema may already exist.

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'DAILY_HELP_BOOKINGS',
      'DAILY_HELP_PROFESSIONAL_SLOTS',
      'DAILY_HELP_PROFESSIONALS',
      'DAILY_HELP_SERVICES'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

CREATE TABLE DAILY_HELP_SERVICES (
  SERVICE_ID VARCHAR2(64) PRIMARY KEY,
  CATEGORY VARCHAR2(100) NOT NULL,
  NAME VARCHAR2(150) NOT NULL,
  DESCRIPTION VARCHAR2(1000),
  PRICING_UNIT VARCHAR2(20) NOT NULL,
  PRICE_PER_HOUR NUMBER(10,2) NOT NULL,
  MIN_HOURS NUMBER(5) NOT NULL,
  IMAGE_URL VARCHAR2(500),
  ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACTIVE IN (0,1)),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_DH_SERVICE_ACTIVE ON DAILY_HELP_SERVICES(ACTIVE, CATEGORY);

CREATE TABLE DAILY_HELP_PROFESSIONALS (
  PROFESSIONAL_ID VARCHAR2(64) PRIMARY KEY,
  FULL_NAME VARCHAR2(150) NOT NULL,
  PHONE VARCHAR2(30) NOT NULL UNIQUE,
  RATING NUMBER(3,2) DEFAULT 0 NOT NULL,
  REVIEW_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  CURRENT_LOCALITY VARCHAR2(150),
  STATUS VARCHAR2(30) DEFAULT 'OFFLINE' NOT NULL,
  VERIFIED NUMBER(1) DEFAULT 1 NOT NULL CHECK (VERIFIED IN (0,1)),
  CURRENT_LATITUDE NUMBER(10,7),
  CURRENT_LONGITUDE NUMBER(10,7),
  REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_DH_PROF_LOCALITY ON DAILY_HELP_PROFESSIONALS(CURRENT_LOCALITY, STATUS, VERIFIED);

CREATE TABLE DAILY_HELP_BOOKINGS (
  BOOKING_ID VARCHAR2(64) PRIMARY KEY,
  SERVICE_ID VARCHAR2(64) NOT NULL REFERENCES DAILY_HELP_SERVICES(SERVICE_ID),
  PROFESSIONAL_ID VARCHAR2(64) REFERENCES DAILY_HELP_PROFESSIONALS(PROFESSIONAL_ID),
  BUYER_NAME VARCHAR2(150) NOT NULL,
  BUYER_PHONE VARCHAR2(30) NOT NULL,
  ADDRESS VARCHAR2(1000) NOT NULL,
  LOCALITY VARCHAR2(150) NOT NULL,
  SCHEDULED_START TIMESTAMP NOT NULL,
  REQUESTED_HOURS NUMBER(4,1) NOT NULL,
  HOURLY_RATE NUMBER(10,2) NOT NULL,
  ESTIMATED_TOTAL NUMBER(10,2) NOT NULL,
  STATUS VARCHAR2(40) DEFAULT 'SEARCHING' NOT NULL,
  START_OTP VARCHAR2(10),
  OTP_EXPIRES_AT TIMESTAMP,
  OTP_ATTEMPTS NUMBER(5) DEFAULT 0 NOT NULL,
  OTP_VERIFIED_AT TIMESTAMP,
  SERVICE_STARTED_AT TIMESTAMP,
  SERVICE_COMPLETED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_DH_BOOKING_BUYER ON DAILY_HELP_BOOKINGS(BUYER_PHONE, CREATED_AT);
CREATE INDEX IDX_DH_BOOKING_PROF ON DAILY_HELP_BOOKINGS(PROFESSIONAL_ID, STATUS, SCHEDULED_START);
CREATE INDEX IDX_DH_BOOKING_MATCH ON DAILY_HELP_BOOKINGS(STATUS, LOCALITY, SCHEDULED_START);

CREATE TABLE DAILY_HELP_PROFESSIONAL_SLOTS (
  SLOT_ID VARCHAR2(64) PRIMARY KEY,
  PROFESSIONAL_ID VARCHAR2(64) NOT NULL REFERENCES DAILY_HELP_PROFESSIONALS(PROFESSIONAL_ID) ON DELETE CASCADE,
  SLOT_DATE DATE NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
  BOOKING_ID VARCHAR2(64),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT UK_DH_PROF_SLOT UNIQUE (PROFESSIONAL_ID, SLOT_DATE, START_TIME, END_TIME)
);

CREATE INDEX IDX_DH_SLOT_LOOKUP ON DAILY_HELP_PROFESSIONAL_SLOTS(SLOT_DATE, STATUS, PROFESSIONAL_ID);

-- Oracle DATE/TIMESTAMP mappings used by LocalTime require time-of-day values.
-- Seed a small production-safe service catalogue; Admin can edit rates/details later.
INSERT INTO DAILY_HELP_SERVICES
  (SERVICE_ID, CATEGORY, NAME, DESCRIPTION, PRICING_UNIT, PRICE_PER_HOUR, MIN_HOURS, ACTIVE)
VALUES
  ('DH-CLEANING', 'Cleaning', 'Home Cleaning', 'Kitchen, rooms and general household cleaning.', 'HOUR', 199, 1, 1);

INSERT INTO DAILY_HELP_SERVICES
  (SERVICE_ID, CATEGORY, NAME, DESCRIPTION, PRICING_UNIT, PRICE_PER_HOUR, MIN_HOURS, ACTIVE)
VALUES
  ('DH-DISHES', 'Kitchen', 'Dishwashing & Kitchen Help', 'Dishwashing and routine kitchen assistance.', 'HOUR', 179, 1, 1);

INSERT INTO DAILY_HELP_SERVICES
  (SERVICE_ID, CATEGORY, NAME, DESCRIPTION, PRICING_UNIT, PRICE_PER_HOUR, MIN_HOURS, ACTIVE)
VALUES
  ('DH-LAUNDRY', 'Laundry', 'Laundry & Folding', 'Washing, drying and folding household clothes.', 'HOUR', 189, 1, 1);

INSERT INTO DAILY_HELP_SERVICES
  (SERVICE_ID, CATEGORY, NAME, DESCRIPTION, PRICING_UNIT, PRICE_PER_HOUR, MIN_HOURS, ACTIVE)
VALUES
  ('DH-COOKING', 'Cooking', 'Home Cooking Assistance', 'Everyday meal preparation and kitchen assistance.', 'HOUR', 229, 2, 1);

COMMIT;
