CREATE TABLE DAILY_HELP_SERVICES (
    SERVICE_ID VARCHAR2(64 CHAR) NOT NULL,
    CATEGORY VARCHAR2(100 CHAR) NOT NULL,
    NAME VARCHAR2(150 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(1000 CHAR),
    PRICING_UNIT VARCHAR2(20 CHAR) DEFAULT 'HOUR' NOT NULL,
    PRICE_PER_HOUR NUMBER(10,2) NOT NULL,
    MIN_HOURS NUMBER(4) DEFAULT 1 NOT NULL,
    IMAGE_URL VARCHAR2(500 CHAR),
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DAILY_HELP_SERVICES PRIMARY KEY (SERVICE_ID)
);

CREATE TABLE DAILY_HELP_PROFESSIONALS (
    PROFESSIONAL_ID VARCHAR2(64 CHAR) NOT NULL,
    FULL_NAME VARCHAR2(150 CHAR) NOT NULL,
    PHONE VARCHAR2(30 CHAR) NOT NULL,
    RATING NUMBER(3,2) DEFAULT 0 NOT NULL,
    REVIEW_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    CURRENT_LOCALITY VARCHAR2(150 CHAR),
    STATUS VARCHAR2(30 CHAR) DEFAULT 'OFFLINE' NOT NULL,
    VERIFIED NUMBER(1) DEFAULT 0 NOT NULL,
    CURRENT_LATITUDE NUMBER(10,7),
    CURRENT_LONGITUDE NUMBER(10,7),
    REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DAILY_HELP_PROF PRIMARY KEY (PROFESSIONAL_ID)
);

CREATE INDEX IDX_DAILY_HELP_PROF_STATUS ON DAILY_HELP_PROFESSIONALS (STATUS, CURRENT_LOCALITY);

CREATE TABLE DAILY_HELP_BOOKINGS (
    BOOKING_ID VARCHAR2(64 CHAR) NOT NULL,
    SERVICE_ID VARCHAR2(64 CHAR) NOT NULL,
    PROFESSIONAL_ID VARCHAR2(64 CHAR),
    BUYER_NAME VARCHAR2(150 CHAR) NOT NULL,
    BUYER_PHONE VARCHAR2(30 CHAR) NOT NULL,
    ADDRESS VARCHAR2(1000 CHAR) NOT NULL,
    LOCALITY VARCHAR2(150 CHAR) NOT NULL,
    SCHEDULED_START TIMESTAMP NOT NULL,
    REQUESTED_HOURS NUMBER(4,1) NOT NULL,
    HOURLY_RATE NUMBER(10,2) NOT NULL,
    ESTIMATED_TOTAL NUMBER(10,2) NOT NULL,
    STATUS VARCHAR2(40 CHAR) NOT NULL,
    START_OTP VARCHAR2(10 CHAR) NOT NULL,
    OTP_VERIFIED_AT TIMESTAMP,
    SERVICE_STARTED_AT TIMESTAMP,
    SERVICE_COMPLETED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DAILY_HELP_BOOKINGS PRIMARY KEY (BOOKING_ID),
    CONSTRAINT FK_DH_BOOK_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES DAILY_HELP_SERVICES(SERVICE_ID),
    CONSTRAINT FK_DH_BOOK_PROF FOREIGN KEY (PROFESSIONAL_ID) REFERENCES DAILY_HELP_PROFESSIONALS(PROFESSIONAL_ID)
);

CREATE INDEX IDX_DH_BOOK_BUYER ON DAILY_HELP_BOOKINGS (BUYER_PHONE, CREATED_AT);
CREATE INDEX IDX_DH_BOOK_STATUS ON DAILY_HELP_BOOKINGS (STATUS, SCHEDULED_START);
