-- Extend the already-applied V7 Daily Help schema without modifying V7 checksum.

ALTER TABLE DAILY_HELP_BOOKINGS ADD (
    OTP_EXPIRES_AT TIMESTAMP,
    OTP_ATTEMPTS NUMBER(5) DEFAULT 0 NOT NULL
);

CREATE TABLE DAILY_HELP_PROFESSIONAL_SLOTS (
    SLOT_ID VARCHAR2(64 CHAR) NOT NULL,
    PROFESSIONAL_ID VARCHAR2(64 CHAR) NOT NULL,
    SLOT_DATE DATE NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'AVAILABLE' NOT NULL,
    BOOKING_ID VARCHAR2(64 CHAR),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DH_PROF_SLOT PRIMARY KEY (SLOT_ID),
    CONSTRAINT FK_DH_SLOT_PROF FOREIGN KEY (PROFESSIONAL_ID)
        REFERENCES DAILY_HELP_PROFESSIONALS(PROFESSIONAL_ID) ON DELETE CASCADE,
    CONSTRAINT UK_DH_PROF_SLOT UNIQUE (PROFESSIONAL_ID, SLOT_DATE, START_TIME, END_TIME)
);

CREATE INDEX IDX_DH_SLOT_LOOKUP
    ON DAILY_HELP_PROFESSIONAL_SLOTS (SLOT_DATE, STATUS, PROFESSIONAL_ID);

CREATE INDEX IDX_DH_BOOK_PROF
    ON DAILY_HELP_BOOKINGS (PROFESSIONAL_ID, STATUS, SCHEDULED_START);

CREATE INDEX IDX_DH_BOOK_MATCH
    ON DAILY_HELP_BOOKINGS (STATUS, LOCALITY, SCHEDULED_START);

CREATE INDEX IDX_DH_SERVICE_ACTIVE
    ON DAILY_HELP_SERVICES (ACTIVE, CATEGORY);

-- Seed the default Daily Help catalogue only when the service is not already present.
MERGE INTO DAILY_HELP_SERVICES s
USING (
    SELECT 'DH-CLEANING' SERVICE_ID, 'Cleaning' CATEGORY, 'Home Cleaning' NAME,
           'Kitchen, rooms and general household cleaning.' DESCRIPTION,
           'HOUR' PRICING_UNIT, 199 PRICE_PER_HOUR, 1 MIN_HOURS FROM dual
    UNION ALL
    SELECT 'DH-DISHES', 'Kitchen', 'Dishwashing & Kitchen Help',
           'Dishwashing and routine kitchen assistance.', 'HOUR', 179, 1 FROM dual
    UNION ALL
    SELECT 'DH-LAUNDRY', 'Laundry', 'Laundry & Folding',
           'Washing, drying and folding household clothes.', 'HOUR', 189, 1 FROM dual
    UNION ALL
    SELECT 'DH-COOKING', 'Cooking', 'Home Cooking Assistance',
           'Everyday meal preparation and kitchen assistance.', 'HOUR', 229, 2 FROM dual
) src
ON (s.SERVICE_ID = src.SERVICE_ID)
WHEN NOT MATCHED THEN
    INSERT (SERVICE_ID, CATEGORY, NAME, DESCRIPTION, PRICING_UNIT, PRICE_PER_HOUR, MIN_HOURS, ACTIVE)
    VALUES (src.SERVICE_ID, src.CATEGORY, src.NAME, src.DESCRIPTION, src.PRICING_UNIT, src.PRICE_PER_HOUR, src.MIN_HOURS, 1);
