ALTER TABLE DAILY_HELP_BOOKINGS MODIFY START_OTP VARCHAR2(10 CHAR) NULL;
ALTER TABLE DAILY_HELP_BOOKINGS ADD OTP_EXPIRES_AT TIMESTAMP;
ALTER TABLE DAILY_HELP_BOOKINGS ADD OTP_ATTEMPTS NUMBER(3) DEFAULT 0 NOT NULL;