-- Buyer precision location + delivery live tracking.
-- Run once against the Oracle schema before deploying the backend changes.

ALTER TABLE USERS ADD (
    ADDRESS_LINE1 VARCHAR2(300),
    LANDMARK VARCHAR2(200),
    FORMATTED_ADDRESS VARCHAR2(500),
    PLACE_ID VARCHAR2(255),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7)
);

ALTER TABLE DELIVERY_AGENTS ADD (
    CURRENT_LATITUDE NUMBER(10,7),
    CURRENT_LONGITUDE NUMBER(10,7),
    LOCATION_UPDATED_AT TIMESTAMP
);

ALTER TABLE ORDERS ADD (
    DELIVERY_LATITUDE NUMBER(10,7),
    DELIVERY_LONGITUDE NUMBER(10,7),
    DELIVERY_PLACE_ID VARCHAR2(255)
);