import React from 'react';
import { MessageSquare, ShoppingBag, Star, TrendingDown, Store } from 'lucide-react';
import { Product } from '../../types';
interface ProductCardProps { product: Product; relatedSellerCount?: number; onCompare: (product: Product) => void; onBargain: (product: Product) => void; onAddToCart: (product: Product) => void; onBuyNow: (product: Product) => void; onViewDetails: (product: Product) => void; }
const getEffectivePrice = (product: Product) => Math.round(product.sellerPrice * (1 - product.additionalDiscountPercent / 100));
export const ProductCard: React.FC<ProductCardProps> = ({ product, relatedSellerCount = 0, onCompare, onBargain, onAddToCart, onBuyNow, onViewDetails }) => { const effectivePrice=getEffectivePrice(product); const savings=Math.max(0,product.mrp-effectivePrice); const discount=product.mrp>0?Math.round((savings/product.mrp)*100):0; return <article className="bg-white rounded-2xl border border-slate-200 hover:border-amber-400 shadow-sm hover:shadow-lg transition-all duration-200 overflow-hidden group"><button onClick={()=>onViewDetails(product)} className="w-full text-left cursor-pointer" aria-label={"View "+product.title+" details"}><div className="relative aspect-square overflow-hidden bg-slate-100"><img src={product.image} alt={product.title} loading="lazy" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"/><div className="absolute top-2.5 left-2.5 flex flex-col gap-1">{discount>0&&<span className="bg-emerald-600 text-white text-[10px] font-extrabold px-2 py-0.5 rounded-full shadow-sm">{discount}% OFF</span>}</div><div className="absolute bottom-2.5 left-2.5 right-2.5 flex items-center justify-between text-[11px] bg-slate-900/80 text-white px-2.5 py-1 rounded-xl"><span className="truncate">{product.sellerLocality}</span><span className="font-extrabold text-amber-300">{product.sellerDistanceKm} km</span></div></div></button><div className="p-2.5 sm:p-4 space-y-2.5 sm:space-y-3"><button onClick={()=>onViewDetails(product)} className="w-full text-left cursor-pointer"><div className="flex items-center justify-between text-[11px] text-slate-500 mb-1"><span className="truncate max-w-[105px] sm:max-w-[150px] font-medium flex items-center gap-1"><Store className="w-3 h-3"/>{product.sellerName}</span><span className="flex items-center gap-1 text-amber-600 font-bold"><Star className="w-3 h-3 fill-amber-400"/>{product.sellerRating}</span></div><h3 className="font-bold text-slate-900 text-sm leading-snug line-clamp-2">{product.title}</h3><p className="text-[11px] text-slate-500">{product.unit}</p></button><div className="pt-2 border-t border-slate-100"><div className="flex items-baseline gap-2"><span className="text-base sm:text-lg font-black text-slate-900">₹{effectivePrice}</span><span className="text-[10px] sm:text-xs text-slate-400 line-through">₹{product.mrp}</span></div><div className="text-[10px] sm:text-[11px] text-emerald-700 font-semibold">Save ₹{savings} locally</div></div><div className="flex items-center justify-end text-[10px] text-slate-500"><span className={product.stock>0?'text-emerald-700 font-bold':'text-rose-600 font-bold'}>{product.stock>0?'In stock':'Out of stock'}</span></div><div className="grid grid-cols-2 gap-1.5">
<button onClick={()=>onAddToCart(product)} disabled={product.stock<=0} className="py-2 sm:py-2.5 bg-amber-500 disabled:bg-slate-300 text-white rounded-xl text-[11px] font-extrabold flex items-center justify-center gap-1"><ShoppingBag className="w-3.5 h-3.5"/>Add to Cart</button>
<button onClick={()=>onBuyNow(product)} disabled={product.stock<=0} className="py-2 sm:py-2.5 bg-slate-900 disabled:bg-slate-300 text-white rounded-xl text-[11px] font-extrabold">Buy Now</button>
</div>
<div className="flex items-center justify-between pt-1 text-[10px]">
<button onClick={()=>onCompare(product)} className="text-amber-700 font-bold hover:underline flex items-center gap-1"><TrendingDown className="w-3 h-3"/>Compare{relatedSellerCount>0?' · '+(relatedSellerCount+1):''}</button>
<button onClick={()=>onBargain(product)} className="text-slate-500 font-semibold hover:text-slate-800 flex items-center gap-1"><MessageSquare className="w-3 h-3"/>Bargain</button>
</div></div></article>; };